### ISSUE TITLE
Python 3.7.3 running issue

### ISSUE THREAD

**Issue by basharatoum** [UTA-REST/MAGBOLTZ-py#1]
After trying to run Magboltz with python 3.7.3, I get the following error:  

```
.
.
.
Original exception was:
Traceback (most recent call last):
  File "/home/bashar/.local/lib/python3.7/site-packages/numpy/lib/npyio.py", line 453, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/bashar/.local/lib/python3.7/site-packages/numpy/lib/format.py", line 722, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False
Exception ignored in: 'CF4.Gas1'
.
.
.
```

**Comment by basharatoum** [comment]
This error occurs because python 3.7.3 uses numpy 1.17.0. Downgrade to numpy 1.16.1.

`pip install numpy==1.16.1 --user`

**Comment by basharatoum** [comment]
This issue shouldn't occur anymore...
